"""RAG 项目的路径与默认配置。"""

from pathlib import Path

CORE_DIR = Path(__file__).resolve().parent
PACKAGE_DIR = CORE_DIR.parent
SRC_DIR = PACKAGE_DIR.parent
PROJECT_DIR = SRC_DIR.parent
RESOURCE_DIR = PROJECT_DIR / "resource"
OUTPUT_DIR = PROJECT_DIR / "output"

DEFAULT_TRACEDR_SAMPLE_INPUT = RESOURCE_DIR / "patient_candidate" / "tracedr_top50" / "test.jsonl"
DEFAULT_RAG_OUTPUT_DIR = OUTPUT_DIR / "rag"
DEFAULT_RAG_CASE_OUTPUT_DIR = DEFAULT_RAG_OUTPUT_DIR / "cases"
DEFAULT_RAG_GENERATION_OUTPUT_DIR = DEFAULT_RAG_OUTPUT_DIR / "generation"
DEFAULT_RAG_EVAL_OUTPUT_DIR = DEFAULT_RAG_OUTPUT_DIR / "eval"
DEFAULT_RAG_TOP_K = 10
DEFAULT_RAG_MAX_EVIDENCES_PER_CANDIDATE = 1
DEFAULT_RAG_GENERATION_LIMIT = 1
DEFAULT_SILICONFLOW_BASE_URL = "https://api.siliconflow.cn/v1"
DEFAULT_SILICONFLOW_CHAT_COMPLETIONS_URL = f"{DEFAULT_SILICONFLOW_BASE_URL}/chat/completions"
DEFAULT_SILICONFLOW_MODEL = "Qwen/Qwen3-30B-A3B-Instruct-2507"
DEFAULT_SILICONFLOW_MAX_TOKENS = 1024
DEFAULT_SILICONFLOW_TEMPERATURE = 0.0
DEFAULT_SILICONFLOW_TIMEOUT_SECONDS = 180
